_target_: src.models.timm_classifier.TimmClassifier

# Model parameters
base_model: tiny_vit_5m_224
num_classes: 2
pretrained: false

# Optimizer parameters
lr: 1e-3
optimizer: Adam
weight_decay: 1e-5
betas: [0.9, 0.999]
eps: 1e-8

# Scheduler parameters
scheduler_patience: 3
scheduler_factor: 0.1

